controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController


diff_cont:
  ros__parameters:
    use_stamped_vel: false
    publish_rate: 50.0

    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.16
    wheel_radius: 0.035

    enable_odom_tf: true

joint_state_broadcaster:
  ros__parameters: {}
